import { Router } from "express";

import { adapt } from "./runtime/express-adapter";

import * as aiAnalyze from "./routes/ai/analyze/route";
import * as aiBriefing from "./routes/ai/briefing/route";
import * as aiOverview from "./routes/ai/overview/route";
import * as airQuality from "./routes/air-quality/route";
import * as arcgis from "./routes/arcgis/route";
import * as balloons from "./routes/balloons/route";
import * as cctv from "./routes/cctv/route";
import * as cctvProxy from "./routes/cctv/proxy/route";
import * as cctvStreamStatus from "./routes/cctv/stream-status/route";
import * as cloudflareRadar from "./routes/cloudflare-radar/route";
import * as conflicts from "./routes/conflicts/route";
import * as countryRisk from "./routes/country-risk/route";
import * as crypto from "./routes/crypto/route";
import * as cyberAttacks from "./routes/cyber-attacks/route";
import * as cyberThreats from "./routes/cyber-threats/route";
import * as earthquakes from "./routes/earthquakes/route";
import * as entityExpand from "./routes/entity/expand/route";
import * as fires from "./routes/fires/route";
import * as flights from "./routes/flights/route";
import * as flightsRouteInfo from "./routes/flights/route-info/route";
import * as frontlines from "./routes/frontlines/route";
import * as gdelt from "./routes/gdelt/route";
import * as gdeltEvents from "./routes/gdelt-events/route";
import * as githubWebhook from "./routes/github-webhook/route";
import * as health from "./routes/health/route";
import * as infrastructure from "./routes/infrastructure/route";
import * as intelligence from "./routes/intelligence/route";
import * as liveNews from "./routes/live-news/route";
import * as malware from "./routes/malware/route";
import * as maritime from "./routes/maritime/route";
import * as markets from "./routes/markets/route";
import * as news from "./routes/news/route";
import * as osintBgp from "./routes/osint/bgp/route";
import * as osintCerts from "./routes/osint/certs/route";
import * as osintCve from "./routes/osint/cve/route";
import * as osintDns from "./routes/osint/dns/route";
import * as osintGithub from "./routes/osint/github/route";
import * as osintIp from "./routes/osint/ip/route";
import * as osintLeaks from "./routes/osint/leaks/route";
import * as osintMac from "./routes/osint/mac/route";
import * as osintPhone from "./routes/osint/phone/route";
import * as osintSanctions from "./routes/osint/sanctions/route";
import * as osintShodan from "./routes/osint/shodan/route";
import * as osintSweep from "./routes/osint/sweep/route";
import * as osintThreats from "./routes/osint/threats/route";
import * as osintWhois from "./routes/osint/whois/route";
import * as proxyTiles from "./routes/proxy-tiles/route";
import * as radar from "./routes/radar/route";
import * as radiation from "./routes/radiation/route";
import * as regionDossier from "./routes/region-dossier/route";
import * as satellites from "./routes/satellites/route";
import * as scanner from "./routes/scanner/route";
import * as scmSuppliers from "./routes/scm-suppliers/route";
import * as sdkIngest from "./routes/sdk/ingest/route";
import * as sdkStream from "./routes/sdk/stream/route";
import * as sentinel from "./routes/sentinel/route";
import * as spaceWeather from "./routes/space-weather/route";
import * as stats from "./routes/stats/route";
import * as weather from "./routes/weather/route";

/**
 * Rutas de elippser (vista /global) portadas desde los route handlers de
 * Next.js. Se montan bajo /api/global/* — ver src/index.ts.
 *
 * Generado por tools/port-elippser/port-backend.js. Los handlers viven en ./routes
 * con su codigo original; el shim de next/server los adapta a Express.
 */
export const globalRouter = Router();

globalRouter.post("/ai/analyze", adapt(aiAnalyze.POST));
globalRouter.post("/ai/briefing", adapt(aiBriefing.POST));
globalRouter.post("/ai/overview", adapt(aiOverview.POST));
globalRouter.get("/air-quality", adapt(airQuality.GET));
globalRouter.get("/arcgis", adapt(arcgis.GET));
globalRouter.get("/balloons", adapt(balloons.GET));
globalRouter.get("/cctv", adapt(cctv.GET));
globalRouter.get("/cctv/proxy", adapt(cctvProxy.GET));
globalRouter.get("/cctv/stream-status", adapt(cctvStreamStatus.GET));
globalRouter.get("/cloudflare-radar", adapt(cloudflareRadar.GET));
globalRouter.get("/conflicts", adapt(conflicts.GET));
globalRouter.get("/country-risk", adapt(countryRisk.GET));
globalRouter.get("/crypto", adapt(crypto.GET));
globalRouter.get("/cyber-attacks", adapt(cyberAttacks.GET));
globalRouter.get("/cyber-threats", adapt(cyberThreats.GET));
globalRouter.get("/earthquakes", adapt(earthquakes.GET));
globalRouter.get("/entity/expand", adapt(entityExpand.GET));
globalRouter.get("/fires", adapt(fires.GET));
globalRouter.get("/flights", adapt(flights.GET));
globalRouter.get("/flights/route-info", adapt(flightsRouteInfo.GET));
globalRouter.get("/frontlines", adapt(frontlines.GET));
globalRouter.get("/gdelt", adapt(gdelt.GET));
globalRouter.get("/gdelt-events", adapt(gdeltEvents.GET));
globalRouter.post("/github-webhook", adapt(githubWebhook.POST));
globalRouter.get("/health", adapt(health.GET));
globalRouter.get("/infrastructure", adapt(infrastructure.GET));
globalRouter.get("/intelligence", adapt(intelligence.GET));
globalRouter.get("/live-news", adapt(liveNews.GET));
globalRouter.get("/malware", adapt(malware.GET));
globalRouter.get("/maritime", adapt(maritime.GET));
globalRouter.get("/markets", adapt(markets.GET));
globalRouter.get("/news", adapt(news.GET));
globalRouter.get("/osint/bgp", adapt(osintBgp.GET));
globalRouter.get("/osint/certs", adapt(osintCerts.GET));
globalRouter.get("/osint/cve", adapt(osintCve.GET));
globalRouter.get("/osint/dns", adapt(osintDns.GET));
globalRouter.get("/osint/github", adapt(osintGithub.GET));
globalRouter.get("/osint/ip", adapt(osintIp.GET));
globalRouter.get("/osint/leaks", adapt(osintLeaks.GET));
globalRouter.get("/osint/mac", adapt(osintMac.GET));
globalRouter.get("/osint/phone", adapt(osintPhone.GET));
globalRouter.get("/osint/sanctions", adapt(osintSanctions.GET));
globalRouter.get("/osint/shodan", adapt(osintShodan.GET));
globalRouter.get("/osint/sweep", adapt(osintSweep.GET));
globalRouter.get("/osint/threats", adapt(osintThreats.GET));
globalRouter.get("/osint/whois", adapt(osintWhois.GET));
globalRouter.get("/proxy-tiles", adapt(proxyTiles.GET));
globalRouter.get("/radar", adapt(radar.GET));
globalRouter.get("/radiation", adapt(radiation.GET));
globalRouter.get("/region-dossier", adapt(regionDossier.GET));
globalRouter.get("/satellites", adapt(satellites.GET));
globalRouter.get("/scanner", adapt(scanner.GET));
globalRouter.get("/scm-suppliers", adapt(scmSuppliers.GET));
globalRouter.post("/sdk/ingest", adapt(sdkIngest.POST));
globalRouter.get("/sdk/ingest", adapt(sdkIngest.GET));
globalRouter.get("/sdk/stream", adapt(sdkStream.GET));
globalRouter.get("/sentinel", adapt(sentinel.GET));
globalRouter.get("/space-weather", adapt(spaceWeather.GET));
globalRouter.get("/stats", adapt(stats.GET));
globalRouter.get("/weather", adapt(weather.GET));
